// <auto-generated />
using System;
using Fysio.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Fysio.Migrations
{
    [DbContext(typeof(FysioDbContext))]
    [Migration("20211004185650_ChangedNameOfTablesFromNLtoEN")]
    partial class ChangedNameOfTablesFromNLtoEN
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Fysio.Models.Patiëntdossier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Behandelingen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Behandelplan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DatumAanmelding")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DatumOntslag")
                        .HasColumnType("datetime2");

                    b.Property<string>("DiagnosOmschrijving")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiagnoseCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoofdbehandelaarEmailaddress")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("IntakeGedaanDoor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IntakeOnderSupervisieVan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Klachten")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Opmerkingen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PatientEmailaddress")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PhysiotherapistEmailaddress")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("StudentEmailaddress")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("HoofdbehandelaarEmailaddress");

                    b.HasIndex("PatientEmailaddress");

                    b.HasIndex("PhysiotherapistEmailaddress");

                    b.HasIndex("StudentEmailaddress");

                    b.ToTable("Patiëntdossiers");
                });

            modelBuilder.Entity("Fysio.Models.Person", b =>
                {
                    b.Property<string>("Emailaddress")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("DayOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PhoneNumber")
                        .HasColumnType("int");

                    b.HasKey("Emailaddress");

                    b.ToTable("Persons");
                });

            modelBuilder.Entity("Fysio.Models.Patient", b =>
                {
                    b.HasBaseType("Fysio.Models.Person");

                    b.Property<int>("Patiëntnumber")
                        .HasColumnType("int");

                    b.ToTable("Patient");
                });

            modelBuilder.Entity("Fysio.Models.Physiotherapist", b =>
                {
                    b.HasBaseType("Fysio.Models.Person");

                    b.Property<int>("BIGNummer")
                        .HasColumnType("int");

                    b.ToTable("Physiotherapist");
                });

            modelBuilder.Entity("Fysio.Models.Student", b =>
                {
                    b.HasBaseType("Fysio.Models.Person");

                    b.Property<int>("Studentnumber")
                        .HasColumnType("int");

                    b.ToTable("Student");
                });

            modelBuilder.Entity("Fysio.Models.Teacher", b =>
                {
                    b.HasBaseType("Fysio.Models.Person");

                    b.Property<int>("StaffNumber")
                        .HasColumnType("int");

                    b.ToTable("Teacher");
                });

            modelBuilder.Entity("Fysio.Models.Patiëntdossier", b =>
                {
                    b.HasOne("Fysio.Models.Physiotherapist", "Hoofdbehandelaar")
                        .WithMany()
                        .HasForeignKey("HoofdbehandelaarEmailaddress");

                    b.HasOne("Fysio.Models.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientEmailaddress");

                    b.HasOne("Fysio.Models.Physiotherapist", "Physiotherapist")
                        .WithMany()
                        .HasForeignKey("PhysiotherapistEmailaddress");

                    b.HasOne("Fysio.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentEmailaddress");

                    b.Navigation("Hoofdbehandelaar");

                    b.Navigation("Patient");

                    b.Navigation("Physiotherapist");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Fysio.Models.Patient", b =>
                {
                    b.HasOne("Fysio.Models.Person", null)
                        .WithOne()
                        .HasForeignKey("Fysio.Models.Patient", "Emailaddress")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Fysio.Models.Physiotherapist", b =>
                {
                    b.HasOne("Fysio.Models.Person", null)
                        .WithOne()
                        .HasForeignKey("Fysio.Models.Physiotherapist", "Emailaddress")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Fysio.Models.Student", b =>
                {
                    b.HasOne("Fysio.Models.Person", null)
                        .WithOne()
                        .HasForeignKey("Fysio.Models.Student", "Emailaddress")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Fysio.Models.Teacher", b =>
                {
                    b.HasOne("Fysio.Models.Person", null)
                        .WithOne()
                        .HasForeignKey("Fysio.Models.Teacher", "Emailaddress")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
