// <auto-generated />
using System;
using DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Fysio.Migrations
{
    [DbContext(typeof(FysioDbContext))]
    partial class FysioDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Domain.DomainModels.Patiëntdossier", b =>
                {
                    b.Property<string>("PatientEmail")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Behandelplan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DatumAanmelding")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DatumOntslag")
                        .HasColumnType("datetime2");

                    b.Property<string>("DiagnosOmschrijving")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiagnoseCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoofdbehandelaarEmailaddress")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("IntakeGedaanDoor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IntakeOnderSupervisieVan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Klachten")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Opmerkingen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TherapyId")
                        .HasColumnType("int");

                    b.HasKey("PatientEmail");

                    b.HasIndex("HoofdbehandelaarEmailaddress");

                    b.HasIndex("TherapyId");

                    b.ToTable("Patiëntdossiers");
                });

            modelBuilder.Entity("Domain.DomainModels.Person", b =>
                {
                    b.Property<string>("Emailaddress")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("DayOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PhoneNumber")
                        .HasColumnType("int");

                    b.HasKey("Emailaddress");

                    b.ToTable("Persons");
                });

            modelBuilder.Entity("Domain.DomainModels.Therapy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("TypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TypeId");

                    b.ToTable("Therapys");
                });

            modelBuilder.Entity("Domain.DomainModels.Vektis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("Id");

                    b.ToTable("Vektis");
                });

            modelBuilder.Entity("Domain.DomainModels.Patient", b =>
                {
                    b.HasBaseType("Domain.DomainModels.Person");

                    b.Property<int>("Patiëntnumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.ToTable("Patient");
                });

            modelBuilder.Entity("Domain.DomainModels.Physiotherapist", b =>
                {
                    b.HasBaseType("Domain.DomainModels.Person");

                    b.Property<int>("BIGNummer")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("Physiotherapist");
                });

            modelBuilder.Entity("Domain.DomainModels.Student", b =>
                {
                    b.HasBaseType("Domain.DomainModels.Person");

                    b.Property<int>("Studentnumber")
                        .HasColumnType("int");

                    b.ToTable("Student");
                });

            modelBuilder.Entity("Domain.DomainModels.Teacher", b =>
                {
                    b.HasBaseType("Domain.DomainModels.Person");

                    b.Property<int>("StaffNumber")
                        .HasColumnType("int");

                    b.ToTable("Teacher");
                });

            modelBuilder.Entity("Domain.DomainModels.Patiëntdossier", b =>
                {
                    b.HasOne("Domain.DomainModels.Physiotherapist", "Hoofdbehandelaar")
                        .WithMany()
                        .HasForeignKey("HoofdbehandelaarEmailaddress");

                    b.HasOne("Domain.DomainModels.Patient", "Patient")
                        .WithOne("Patiëntdossier")
                        .HasForeignKey("Domain.DomainModels.Patiëntdossier", "PatientEmail")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.DomainModels.Therapy", "Therapy")
                        .WithMany()
                        .HasForeignKey("TherapyId");

                    b.Navigation("Hoofdbehandelaar");

                    b.Navigation("Patient");

                    b.Navigation("Therapy");
                });

            modelBuilder.Entity("Domain.DomainModels.Therapy", b =>
                {
                    b.HasOne("Domain.DomainModels.Vektis", "Type")
                        .WithMany()
                        .HasForeignKey("TypeId");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("Domain.DomainModels.Patient", b =>
                {
                    b.HasOne("Domain.DomainModels.Person", null)
                        .WithOne()
                        .HasForeignKey("Domain.DomainModels.Patient", "Emailaddress")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.DomainModels.Physiotherapist", b =>
                {
                    b.HasOne("Domain.DomainModels.Person", null)
                        .WithOne()
                        .HasForeignKey("Domain.DomainModels.Physiotherapist", "Emailaddress")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.DomainModels.Student", b =>
                {
                    b.HasOne("Domain.DomainModels.Person", null)
                        .WithOne()
                        .HasForeignKey("Domain.DomainModels.Student", "Emailaddress")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.DomainModels.Teacher", b =>
                {
                    b.HasOne("Domain.DomainModels.Person", null)
                        .WithOne()
                        .HasForeignKey("Domain.DomainModels.Teacher", "Emailaddress")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.DomainModels.Patient", b =>
                {
                    b.Navigation("Patiëntdossier");
                });
#pragma warning restore 612, 618
        }
    }
}
